# Jekyll Digital Collection Generator

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site settings
# title appears in the header
title: "Adult Salmon and Steelhead Migration Studies: 1996-2014" # Fish Ecology Research Lab Collection
# tagline appears in the header, should be short
tagline: "A collection of scientific reports and datasets from University of Idaho's Fish Ecology Research Lab"
# description is for metadata tags
# might appear in search result lists, keep around 160 characters max
description: "A collection of scientific reports and datasets from University of Idaho's Fish Ecology Research Lab related to Adult Salmon and Steelhead Migration Studies 1996-2014."
# for metatags
keywords: salmon; columbia river; snake river; fish migration; university of idaho; scientific reports; Idaho
# contact person
email: ewilliamson@uidaho.edu
collection-date: "2019"
# Organization branding
organization-name: "Digital Initiatives, University of Idaho Library"
organization-link: https://www.lib.uidaho.edu/digital/
organization-logo-banner: https://www.lib.uidaho.edu/media/digital/justdi_logo_sm.png
organization-logo-nav: https://www.lib.uidaho.edu/media/digital/bannerlogo_allwhite.png

# images
# give filename as it appears in "objects" dir (location given below)
# banner-image appears in index header
banner-image: ferl-river.jpg
banner-image-alt: river
home-title-y-padding: 2em
# featured-image appears in meta tags
# represents the collection in other aggregations
featured-image: tagging_fish.jpg
featured-image-alt: researcher tagging salmon

# url variables
# library's domain (only changed if using github pages)
url: https://www.lib.uidaho.edu
# location on the website, normally in /digital
# e.g. /digital/hjccc
baseurl: /digital/ferl
# CDM collection alias
collection-id: ferl
# Objects dir location
objects: https://www.lib.uidaho.edu/digital/objects/ferl
source-code: https://github.com/uidaholib/FERL_source

# base url for our CDM server
cdm-url: https://digital.lib.uidaho.edu
# url to the shared assets folder on Digital
digital-assets: https://www.lib.uidaho.edu/assets

# google-cse-id:

# Dev variables: 
# choose metadata set, i.e. easily switch between full or dev version
# be sure to also change page_gen data setting!
metadata: ferl

# collection display variables 
# see _data/metadata-fields.csv

# page gen settings https://github.com/avillafiorita/jekyll-datapage_gen
page_gen:
  - data: 'ferl'
    template: 'items'
    name: 'object-id'
    dir: 'data'
    extension: 'html'    

exclude: [docs, 'Rakefile']

# compress CSS output
sass:
  style: compressed
